import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.chatbot': '🤖 AI Chatbot',
    'nav.essentialPages': 'Essential Pages',
    'nav.gallery': 'Gallery',
    'nav.schemes': 'Government Schemes',
    'nav.faq': 'FAQ',
    'nav.resources': 'Resources',
    'nav.shop': 'Shop',
    'nav.getStarted': 'Get Started Now',

    // Hero
    'hero.badge': 'We are Producing Natural Products',
    'hero.title': 'KisanSaathi Smart Farming Assistant',
    'hero.subtitle': 'Ask about your crops using voice and get instant guidance',
    'hero.schemes': 'Government Schemes',
    'hero.services': 'See All Service',

    // Services
    'services.title': 'Smart Farming Solutions',
    'services.chatbot': 'AI Chatbot',
    'services.chatbot_desc': 'Talk to KisanSathi AI. Ask about crops, fertilizer, diseases, weather, and more. Voice and text support.',
    'services.crop': 'Crop Recommendation',
    'services.crop_desc': 'Get personalized crop recommendations using AI, voice input, or seasonal data.',
    'services.fertilizer': 'Fertilizer Recommendation',
    'services.fertilizer_desc': 'Receive optimal fertilizer suggestions to maximize crop yield and soil health.',
    'services.disease': 'Disease Detection',
    'services.disease_desc': 'Identify plant diseases early using AI-powered image analysis for timely intervention.',
    'services.weather': 'Weather & Alerts',
    'services.weather_desc': 'Get real-time weather alerts and crop-specific recommendations based on current conditions.',
    'services.reminders': 'Smart Reminders',
    'services.reminders_desc': 'Track your crops with automated reminders for every task throughout the season.',
    'services.getStarted': 'Get Started',

    // Shop Preview
    'shop.featured': 'Featured Products',
    'shop.title': '🧪 Agricultural Medicines & Fertilizers',
    'shop.subtitle': 'Quality pesticides, fertilizers, and bio-products for healthy crops',
    'shop.buyAmazon': 'Buy on Amazon',
    'shop.viewAll': 'View All Products',

    // About
    'about.title': 'About KisanSathi',
    'about.heading': 'Smart Farming Assistant for Modern Farmers',
    'about.talk': 'Talk to AI Assistant',
    'about.click': 'Click the microphone to start chatting',
    'about.voice': '🎤 Voice & Text Support',
    'about.ai': 'AI-Powered Crop Recommendations',
    'about.ai_desc': 'Get personalized crop suggestions based on your soil conditions, weather patterns, and location using advanced machine learning.',
    'about.disease': 'Disease Detection & Treatment',
    'about.disease_desc': 'Upload crop images to identify diseases instantly and receive organic and chemical treatment recommendations.',
    'about.weather': 'Real-Time Weather Alerts',
    'about.weather_desc': 'Get weather-based farming alerts and recommendations to protect your crops from adverse conditions.',
    'about.voice_support': 'Voice & Text Support',
    'about.voice_support_desc': 'Ask questions in Hindi or English using voice or text. Get instant guidance from our AI assistant.',

    // How We Work
    'howwe.title': 'How KisanSathi Works',
    'howwe.subtitle': 'Get instant farming guidance through voice, images, and AI analysis. Our smart system understands your crop needs and provides timely recommendations.',
    'howwe.step1': 'Speak or Upload',
    'howwe.step1_desc': 'Ask your question using voice or upload a crop image',
    'howwe.step2': 'AI Understands',
    'howwe.step2_desc': 'System analyzes your crop, soil, and current condition',
    'howwe.step3': 'Smart Decision',
    'howwe.step3_desc': 'Rule-based logic decides the best action for your crop',
    'howwe.step4': 'Get Guidance',
    'howwe.step4_desc': 'Receive clear instructions and timely reminders',

    // FAQ
    'faq.title': 'How can KisanSathi help?',
    'faq.q1': 'How does KisanSathi help with crop selection?',
    'faq.a1': 'KisanSathi uses AI to analyze your soil conditions, weather, and location to recommend the best crops for your farm. Simply provide your soil parameters or upload a soil report.',
    'faq.q2': 'Can I get disease detection for my crops?',
    'faq.a2': 'Yes! Upload a photo of your affected crop, and our AI will identify the disease and suggest treatment options including organic and chemical solutions.',
    'faq.q3': 'How do I use the voice assistant?',
    'faq.a3': 'Click the microphone button on the chatbot page and ask your farming questions in Hindi or English. The AI will respond with guidance and recommendations.',
    'faq.q4': 'What fertilizers do you recommend?',
    'faq.a4': 'Based on your crop type and soil analysis, KisanSathi recommends specific fertilizers with dosage information. You can also browse our shop for direct purchase.',
    'faq.q5': 'Are government schemes available?',
    'faq.a5': 'Yes! Check our Government Schemes page to see ongoing and upcoming schemes like PM-KISAN, PMFBY, and others with eligibility criteria and application steps.',
    'faq.q6': 'Can I get weather-based farming alerts?',
    'faq.a6': 'Absolutely! Our system provides real-time weather alerts and farming recommendations based on current weather conditions in your area.',

    // Footer
    'footer.features': 'Features',
    'footer.quickLinks': 'Quick Links',
    'footer.subscribe': 'Subscribe Newsletter',
    'footer.subscribe_desc': 'Get farming tips and updates.',
    'footer.email': 'Email Address',
    'footer.subscribeBtn': 'Subscribe Now',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.copyright': '© 2026 KisanSathi. All Rights Reserved.',
    'footer.shop': 'Shop',
    'footer.contact': 'Contact',

    // Auth
    'auth.title': '🌾 KisanSathi - Farmer Portal',
    'auth.subtitle': 'Join thousands of farmers using AI-powered smart agriculture solutions',
    'auth.login': '🔐 Login',
    'auth.signup': '✍️ Sign Up',
    'auth.welcome': 'Welcome Back!',
    'auth.create': 'Create Your Account',
    'auth.login_desc': 'Login to access your farming dashboard',
    'auth.signup_desc': 'Join KisanSathi and get smart farming guidance',
    'auth.name': 'Full Name',
    'auth.email': 'Email Address',
    'auth.mobile': 'Mobile Number',
    'auth.agriculture': 'Type of Agriculture',
    'auth.password': 'Password',
    'auth.confirm': 'Confirm Password',
    'auth.loginBtn': '🔓 Login Now',
    'auth.signupBtn': '✅ Create Account',
    'auth.smartFarming': 'Smart Farming',
    'auth.easyAccess': 'Easy Access',
    'auth.aiAssistant': 'AI Assistant',
    'auth.tip': '💡 Tip:',
    'auth.tipLogin': 'New farmer? Click Sign Up to join our community!',
    'auth.tipSignup': 'Already registered? Click Login to continue!',

    // Government Schemes
    'schemes.title': '🏛️ Government Schemes',
    'schemes.subtitle': 'Explore agricultural schemes and subsidies available for farmers',
    'schemes.ongoing': 'Ongoing Schemes',
    'schemes.upcoming': 'Upcoming Schemes',
    'schemes.description': 'Description',
    'schemes.benefits': 'Key Benefits',
    'schemes.eligibility': 'Eligibility',
    'schemes.applyMethod': 'How to Apply',
    'schemes.applyNow': 'Apply Now',
    'schemes.howToApply': '📝 How to Apply',
    'schemes.checkEligibility': 'Check Eligibility',
    'schemes.checkEligibilityDesc': 'Verify if you meet the scheme requirements',
    'schemes.gatherDocs': 'Gather Documents',
    'schemes.gatherDocsDesc': 'Collect land records, ID, bank details',
    'schemes.applyOnline': 'Apply Online/Offline',
    'schemes.applyOnlineDesc': 'Submit application through portal or office',
    'schemes.trackStatus': 'Track Status',
    'schemes.trackStatusDesc': 'Monitor application and receive benefits',
    'schemes.requiredDocs': 'Required Documents',
    'schemes.needHelp': '📞 Need Help?',
    'schemes.helplineTitle': 'Agriculture Ministry Helpline',
    'schemes.helplineNumber': '1800-180-1551',
    'schemes.officialPortal': 'Official Portal',
    'schemes.officialPortalUrl': 'pmkisan.gov.in',
    'schemes.localOffice': 'Local Agriculture Office',
    'schemes.localOfficeDesc': 'Visit your nearest office',
    'schemes.doc1': 'Aadhar Card / Voter ID',
    'schemes.doc2': 'Land Records (Jamabandi/Patta)',
    'schemes.doc3': 'Bank Account Details',
    'schemes.doc4': 'Mobile Number & Email',
    'schemes.doc5': 'Passport Size Photo',
    'schemes.doc6': 'Income Certificate (if applicable)',
    'schemes.ministry': 'Ministry',
    'schemes.budget': 'Budget',
    'schemes.launchDate': 'Launch',
    'schemes.status': 'Status',
    'schemes.step': 'Step',

    // Shop
    'shop.pageTitle': '🧪 Agricultural Medicines & Fertilizers',
    'shop.pageSubtitle': 'Quality pesticides, fertilizers, and bio-products for healthy crops',
    'shop.buyAmazon': 'Amazon',
    'shop.buyFlipkart': 'Flipkart',

    // FAQ Page
    'faqpage.title': 'FAQ',
    'faqpage.subtitle': 'Have a Question? Check Out Our FAQ for Quick Help',
    'faqpage.q1': 'What types of produce do you grow?',
    'faqpage.a1': 'We grow a wide range of fresh produce, including fruits like strawberries and grapes, vegetables such as tomatoes, carrots, and leafy greens, as well as herbs and specialty crops like microgreens and gourmet vegetables.',
    'faqpage.q2': 'How can I purchase your products?',
    'faqpage.a2': 'You can purchase our products directly from our farm, at local farmers\' markets, or through our online store. We also offer subscription boxes for regular deliveries of fresh, seasonal produce.',
    'faqpage.q3': 'Do you offer farm tours?',
    'faqpage.a3': 'Yes! We offer guided farm tours where you can see our sustainable farming practices in action. Tours are available on weekends and can be booked through our website or by calling us directly.',
    'faqpage.q4': 'Do you use any chemicals or pesticides?',
    'faqpage.a4': 'No, we are committed to 100% organic farming practices. We use natural pest control methods, companion planting, and organic fertilizers to ensure our produce is chemical-free and safe for consumption.',
    'faqpage.q5': 'Do you sell organic seeds or plants?',
    'faqpage.a5': 'Yes, we sell a variety of organic seeds and starter plants. Visit our shop section or come to the farm to browse our selection of heirloom and organic varieties perfect for home gardening.',
    'faqpage.q6': 'How do I market my farm\'s produce effectively?',
    'faqpage.a6': 'Effective marketing includes building a strong online presence, participating in local farmers\' markets, creating a CSA program, and leveraging social media to share your farm\'s story and connect with customers.',
    'faqpage.q7': 'What are the benefits of composting on a farm?',
    'faqpage.a7': 'Composting enriches soil with essential nutrients, improves soil structure and water retention, reduces the need for chemical fertilizers, and helps divert organic waste from landfills, contributing to a more sustainable farming cycle.',
    'faqpage.q8': 'How do I manage pests organically?',
    'faqpage.a8': 'Organic pest management includes using beneficial insects, companion planting, crop rotation, natural sprays like neem oil, and maintaining healthy soil to build plant resistance against pests and diseases.',

    // Weather Component
    'weather.title': '🌤️ Weather & Alerts',
    'weather.subtitle': 'Get real-time weather alerts for your farming',
    'weather.enterCity': 'Enter City Name',
    'weather.placeholder': 'e.g., Delhi, Mumbai, Bangalore',
    'weather.getWeather': 'Get Weather',
    'weather.loading': 'Loading...',
    'weather.temperature': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.rainfall': 'Rainfall',
    'weather.windSpeed': 'Wind Speed',
    'weather.conditions': 'Conditions',
    'weather.highDisease': 'High - Disease Risk',
    'weather.lowPest': 'Low - Pest Risk',
    'weather.normal': 'Normal',
    'weather.heavyRain': 'Heavy Rain',
    'weather.moderate': 'Moderate',
    'weather.light': 'Light',
    'weather.strong': 'Strong',
    'weather.recommendation': 'Farming Recommendation',
    'weather.speak': '🔊 Speak',
    'weather.alerts': 'Weather Alerts',
    'weather.recommendations': 'Recommendations:',
    'weather.affectedCrops': 'Affected Crops:',
    'weather.actionRequired': '⚠️ Action Required',
    'weather.speakAlert': '🔊 Speak Alert',
    'weather.cropAlerts': '🌾 Crop-Specific Alerts',
    'weather.selectCrop': 'Select Crop',
    'weather.getCropAlerts': 'Get Crop Alerts',
    'weather.noAlerts': 'No specific alerts for',
    'weather.favorable': 'Conditions are favorable!',

    // Voice Assistant
    'voice.title': '🎤 Farming AI Assistant',
    'voice.subtitle': 'Ask any farming question in voice or text',
    'voice.language': 'Language',
    'voice.crop': 'Crop (Optional)',
    'voice.cropPlaceholder': 'e.g., moong, rice',
    'voice.location': 'Location (Optional)',
    'voice.locationPlaceholder': 'e.g., Delhi, Punjab',
    'voice.askQuestion': 'Ask your farming question...',
    'voice.typeOrSpeak': 'Type or speak your question...',
    'voice.speak': 'Speak',
    'voice.stop': 'Stop',
    'voice.send': 'Send',
    'voice.howToWater': 'How to water?',
    'voice.howToFertilize': 'How to fertilize?',
    'voice.pestControl': 'Pest control?',
    'voice.whenToHarvest': 'When to harvest?',
    'voice.copy': 'Copy',
    'voice.tip': 'Tip:',
    'voice.tipText': 'Tell the AI your crop name and location for better answers.',
    'voice.english': 'English',
    'voice.hindi': 'Hindi',

    // Chatbot Component
    'chatbot.title': '🌾 KisanSathi AI',
    'chatbot.subtitle': 'Your farming assistant',
    'chatbot.newChat': 'New Chat',
    'chatbot.noConversations': 'No conversations yet',
    'chatbot.clear': 'Clear',
    'chatbot.clearConfirm': 'Clear all messages?',
    'chatbot.cropSelection': 'Crop Selection',
    'chatbot.cropSelectionDesc': 'Kaunsi fasal lagaun?',
    'chatbot.fertilizer': 'Fertilizer',
    'chatbot.fertilizerDesc': 'Khad kaise lagaun?',
    'chatbot.diseaseHelp': 'Disease Help',
    'chatbot.diseaseHelpDesc': 'Meri fasal mein bimari hai',
    'chatbot.weatherAdvice': 'Weather Advice',
    'chatbot.weatherAdviceDesc': 'Aaj barish aa sakti hai',
    'chatbot.placeholder': 'Ask about crops, fertilizer, diseases, weather...',
    'chatbot.speak': 'Speak',
    'chatbot.copy': 'Copy',
    'chatbot.uploadFile': 'Upload image or PDF',
    'chatbot.errorConnecting': 'Error connecting to server',
    'chatbot.errorProcessing': 'Error processing message',

    // Banner Component
    'banner.clientsReview': '100K+ Client With Positive Reviews',
    'banner.healthyLife': 'Healthy Life With Fresh Products',
    'banner.organic': 'Organic',
    'banner.farming': 'Farming',
    'banner.vegetables': 'Vegetables',
    'banner.agro': 'Agro',
  },
  hi: {
    // Navbar
    'nav.home': 'होम',
    'nav.chatbot': '🤖 एआई चैटबॉट',
    'nav.essentialPages': 'आवश्यक पृष्ठ',
    'nav.gallery': 'गैलरी',
    'nav.schemes': 'सरकारी योजनाएं',
    'nav.faq': 'सामान्य प्रश्न',
    'nav.resources': 'संसाधन',
    'nav.shop': 'दुकान',
    'nav.getStarted': 'अभी शुरू करें',

    // Hero
    'hero.badge': 'हम प्राकृतिक उत्पाद बना रहे हैं',
    'hero.title': 'किसानसाथी स्मार्ट खेती सहायक',
    'hero.subtitle': 'अपनी फसलों के बारे में पूछें और तुरंत मार्गदर्शन प्राप्त करें',
    'hero.schemes': 'सरकारी योजनाएं',
    'hero.services': 'सभी सेवाएं देखें',

    // Services
    'services.title': 'स्मार्ट खेती समाधान',
    'services.chatbot': 'एआई चैटबॉट',
    'services.chatbot_desc': 'किसानसाथी एआई से बात करें। फसलों, खाद, बीमारियों, मौसम और बहुत कुछ के बारे में पूछें। आवाज और पाठ समर्थन।',
    'services.crop': 'फसल की सिफारिश',
    'services.crop_desc': 'एआई, आवाज इनपुट या मौसमी डेटा का उपयोग करके व्यक्तिगत फसल सिफारिशें प्राप्त करें।',
    'services.fertilizer': 'खाद की सिफारिश',
    'services.fertilizer_desc': 'फसल की पैदावार और मिट्टी के स्वास्थ्य को अधिकतम करने के लिए इष्टतम खाद सुझाव प्राप्त करें।',
    'services.disease': 'रोग का पता लगाना',
    'services.disease_desc': 'समय पर हस्तक्षेप के लिए एआई-संचालित छवि विश्लेषण का उपयोग करके पौधों की बीमारियों की जल्दी पहचान करें।',
    'services.weather': 'मौसम और सतर्कता',
    'services.weather_desc': 'वर्तमान स्थितियों के आधार पर रीयल-टाइम मौसम सतर्कता और फसल-विशिष्ट सिफारिशें प्राप्त करें।',
    'services.reminders': 'स्मार्ट रिमाइंडर',
    'services.reminders_desc': 'पूरे मौसम में हर कार्य के लिए स्वचालित रिमाइंडर के साथ अपनी फसलों को ट्रैक करें।',
    'services.getStarted': 'शुरू करें',

    // Shop Preview
    'shop.featured': 'विशेष उत्पाद',
    'shop.title': '🧪 कृषि दवाएं और खाद',
    'shop.subtitle': 'स्वस्थ फसलों के लिए गुणवत्ता कीटनाशक, खाद और जैव-उत्पाद',
    'shop.buyAmazon': 'अमेज़न पर खरीदें',
    'shop.viewAll': 'सभी उत्पाद देखें',

    // About
    'about.title': 'किसानसाथी के बारे में',
    'about.heading': 'आधुनिक किसानों के लिए स्मार्ट खेती सहायक',
    'about.talk': 'एआई सहायक से बात करें',
    'about.click': 'चैट करना शुरू करने के लिए माइक्रोफोन पर क्लिक करें',
    'about.voice': '🎤 आवाज और पाठ समर्थन',
    'about.ai': 'एआई-संचालित फसल सिफारिशें',
    'about.ai_desc': 'अपनी मिट्टी की स्थिति, मौसम के पैटर्न और स्थान के आधार पर व्यक्तिगत फसल सुझाव प्राप्त करें।',
    'about.disease': 'रोग का पता लगाना और उपचार',
    'about.disease_desc': 'फसल की तस्वीरें अपलोड करें और रोगों की तुरंत पहचान करें और जैविक और रासायनिक उपचार सिफारिशें प्राप्त करें।',
    'about.weather': 'रीयल-टाइम मौसम सतर्कता',
    'about.weather_desc': 'अपनी फसलों को प्रतिकूल परिस्थितियों से बचाने के लिए मौसम-आधारित खेती सतर्कता और सिफारिशें प्राप्त करें।',
    'about.voice_support': 'आवाज और पाठ समर्थन',
    'about.voice_support_desc': 'हिंदी या अंग्रेजी में आवाज या पाठ का उपयोग करके प्रश्न पूछें। हमारे एआई सहायक से तुरंत मार्गदर्शन प्राप्त करें।',

    // How We Work
    'howwe.title': 'किसानसाथी कैसे काम करता है',
    'howwe.subtitle': 'आवाज, छवियों और एआई विश्लेषण के माध्यम से तुरंत खेती मार्गदर्शन प्राप्त करें। हमारी स्मार्ट प्रणाली आपकी फसल की जरूरतों को समझती है और समय पर सिफारिशें प्रदान करती है।',
    'howwe.step1': 'बोलें या अपलोड करें',
    'howwe.step1_desc': 'अपना प्रश्न आवाज से पूछें या फसल की छवि अपलोड करें',
    'howwe.step2': 'एआई समझता है',
    'howwe.step2_desc': 'सिस्टम आपकी फसल, मिट्टी और वर्तमान स्थिति का विश्लेषण करता है',
    'howwe.step3': 'स्मार्ट निर्णय',
    'howwe.step3_desc': 'नियम-आधारित तर्क आपकी फसल के लिए सर्वोत्तम कार्रवाई तय करता है',
    'howwe.step4': 'मार्गदर्शन प्राप्त करें',
    'howwe.step4_desc': 'स्पष्ट निर्देश और समय पर रिमाइंडर प्राप्त करें',

    // FAQ
    'faq.title': 'किसानसाथी कैसे मदद कर सकता है?',
    'faq.q1': 'किसानसाथी फसल चयन में कैसे मदद करता है?',
    'faq.a1': 'किसानसाथी आपकी मिट्टी की स्थिति, मौसम और स्थान का विश्लेषण करने के लिए एआई का उपयोग करता है ताकि आपके खेत के लिए सर्वोत्तम फसलों की सिफारिश की जा सके।',
    'faq.q2': 'क्या मुझे अपनी फसलों के लिए रोग का पता लगाना मिल सकता है?',
    'faq.a2': 'हां! अपनी प्रभावित फसल की एक तस्वीर अपलोड करें, और हमारा एआई रोग की पहचान करेगा और जैविक और रासायनिक समाधान सहित उपचार विकल्प सुझाएगा।',
    'faq.q3': 'मैं आवाज सहायक का उपयोग कैसे करूं?',
    'faq.a3': 'चैटबॉट पृष्ठ पर माइक्रोफोन बटन पर क्लिक करें और हिंदी या अंग्रेजी में अपने खेती के प्रश्न पूछें। एआई मार्गदर्शन और सिफारिशों के साथ प्रतिक्रिया देगा।',
    'faq.q4': 'आप कौन सी खाद की सिफारिश करते हैं?',
    'faq.a4': 'आपकी फसल के प्रकार और मिट्टी विश्लेषण के आधार पर, किसानसाथी खुराक की जानकारी के साथ विशिष्ट खाद की सिफारिश करता है।',
    'faq.q5': 'क्या सरकारी योजनाएं उपलब्ध हैं?',
    'faq.a5': 'हां! हमारी सरकारी योजनाएं पृष्ठ देखें जहां आप पीएम-किसान, पीएमएफबीवाई और अन्य योजनाओं को पात्रता मानदंड और आवेदन चरणों के साथ देख सकते हैं।',
    'faq.q6': 'क्या मुझे मौसम-आधारित खेती सतर्कता मिल सकती है?',
    'faq.a6': 'बिल्कुल! हमारी प्रणाली आपके क्षेत्र में वर्तमान मौसम स्थितियों के आधार पर रीयल-टाइम मौसम सतर्कता और खेती सिफारिशें प्रदान करती है।',

    // Footer
    'footer.features': 'विशेषताएं',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.subscribe': 'न्यूजलेटर की सदस्यता लें',
    'footer.subscribe_desc': 'खेती के सुझाव और अपडेट प्राप्त करें।',
    'footer.email': 'ईमेल पता',
    'footer.subscribeBtn': 'अभी सदस्यता लें',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'उपयोग की शर्तें',
    'footer.copyright': '© 2026 किसानसाथी। सर्वाधिकार सुरक्षित।',
    'footer.shop': 'दुकान',
    'footer.contact': 'संपर्क',

    // Auth
    'auth.title': '🌾 किसानसाथी - किसान पोर्टल',
    'auth.subtitle': 'एआई-संचालित स्मार्ट कृषि समाधान का उपयोग करने वाले हजारों किसानों से जुड़ें',
    'auth.login': '🔐 लॉगिन',
    'auth.signup': '✍️ साइन अप',
    'auth.welcome': 'स्वागत है!',
    'auth.create': 'अपना खाता बनाएं',
    'auth.login_desc': 'अपने खेती डैशबोर्ड तक पहुंचने के लिए लॉगिन करें',
    'auth.signup_desc': 'किसानसाथी से जुड़ें और स्मार्ट खेती मार्गदर्शन प्राप्त करें',
    'auth.name': 'पूरा नाम',
    'auth.email': 'ईमेल पता',
    'auth.mobile': 'मोबाइल नंबर',
    'auth.agriculture': 'कृषि का प्रकार',
    'auth.password': 'पासवर्ड',
    'auth.confirm': 'पासवर्ड की पुष्टि करें',
    'auth.loginBtn': '🔓 अभी लॉगिन करें',
    'auth.signupBtn': '✅ खाता बनाएं',
    'auth.smartFarming': 'स्मार्ट खेती',
    'auth.easyAccess': 'आसान पहुंच',
    'auth.aiAssistant': 'एआई सहायक',
    'auth.tip': '💡 सुझाव:',
    'auth.tipLogin': 'नए किसान? हमारे समुदाय में शामिल होने के लिए साइन अप पर क्लिक करें!',
    'auth.tipSignup': 'पहले से पंजीकृत? जारी रखने के लिए लॉगिन पर क्लिक करें!',

    // Government Schemes
    'schemes.title': '🏛️ सरकारी योजनाएं',
    'schemes.subtitle': 'किसानों के लिए उपलब्ध कृषि योजनाओं और सब्सिडी का अन्वेषण करें',
    'schemes.ongoing': 'चल रही योजनाएं',
    'schemes.upcoming': 'आने वाली योजनाएं',
    'schemes.description': 'विवरण',
    'schemes.benefits': 'मुख्य लाभ',
    'schemes.eligibility': 'पात्रता',
    'schemes.applyMethod': 'आवेदन कैसे करें',
    'schemes.applyNow': 'अभी आवेदन करें',
    'schemes.howToApply': '📝 आवेदन कैसे करें',
    'schemes.checkEligibility': 'पात्रता जांचें',
    'schemes.checkEligibilityDesc': 'सत्यापित करें कि आप योजना की आवश्यकताओं को पूरा करते हैं',
    'schemes.gatherDocs': 'दस्तावेज एकत्र करें',
    'schemes.gatherDocsDesc': 'भूमि रिकॉर्ड, आईडी, बैंक विवरण एकत्र करें',
    'schemes.applyOnline': 'ऑनलाइन/ऑफलाइन आवेदन करें',
    'schemes.applyOnlineDesc': 'पोर्टल या कार्यालय के माध्यम से आवेदन जमा करें',
    'schemes.trackStatus': 'स्थिति ट्रैक करें',
    'schemes.trackStatusDesc': 'आवेदन की निगरानी करें और लाभ प्राप्त करें',
    'schemes.requiredDocs': 'आवश्यक दस्तावेज',
    'schemes.needHelp': '📞 मदद चाहिए?',
    'schemes.helplineTitle': 'कृषि मंत्रालय हेल्पलाइन',
    'schemes.helplineNumber': '1800-180-1551',
    'schemes.officialPortal': 'आधिकारिक पोर्टल',
    'schemes.officialPortalUrl': 'pmkisan.gov.in',
    'schemes.localOffice': 'स्थानीय कृषि कार्यालय',
    'schemes.localOfficeDesc': 'अपने निकटतम कार्यालय का दौरा करें',
    'schemes.doc1': 'आधार कार्ड / मतदाता पहचान पत्र',
    'schemes.doc2': 'भूमि रिकॉर्ड (जमाबंदी/पट्टा)',
    'schemes.doc3': 'बैंक खाता विवरण',
    'schemes.doc4': 'मोबाइल नंबर और ईमेल',
    'schemes.doc5': 'पासपोर्ट आकार की फोटो',
    'schemes.doc6': 'आय प्रमाण पत्र (यदि लागू हो)',
    'schemes.ministry': 'मंत्रालय',
    'schemes.budget': 'बजट',
    'schemes.launchDate': 'लॉन्च',
    'schemes.status': 'स्थिति',
    'schemes.step': 'चरण',

    // Shop
    'shop.pageTitle': '🧪 कृषि दवाएं और खाद',
    'shop.pageSubtitle': 'स्वस्थ फसलों के लिए गुणवत्ता कीटनाशक, खाद और जैव-उत्पाद',
    'shop.buyAmazon': 'अमेज़न',
    'shop.buyFlipkart': 'फ्लिपकार्ट',

    // FAQ Page
    'faqpage.title': 'सामान्य प्रश्न',
    'faqpage.subtitle': 'कोई सवाल है? त्वरित सहायता के लिए हमारे FAQ देखें',
    'faqpage.q1': 'आप किस प्रकार की उपज उगाते हैं?',
    'faqpage.a1': 'हम स्ट्रॉबेरी और अंगूर जैसे फलों, टमाटर, गाजर और पत्तेदार सब्जियों जैसी सब्जियों, साथ ही माइक्रोग्रीन्स और गोरमेट सब्जियों जैसी विशेष फसलों सहित विभिन्न प्रकार की ताजी उपज उगाते हैं।',
    'faqpage.q2': 'मैं आपके उत्पाद कैसे खरीद सकता हूं?',
    'faqpage.a2': 'आप हमारे खेत से सीधे, स्थानीय किसानों के बाजार में, या हमारे ऑनलाइन स्टोर के माध्यम से हमारे उत्पाद खरीद सकते हैं। हम ताजी, मौसमी उपज की नियमित डिलीवरी के लिए सदस्यता बॉक्स भी प्रदान करते हैं।',
    'faqpage.q3': 'क्या आप खेत के दौरे की पेशकश करते हैं?',
    'faqpage.a3': 'हां! हम निर्देशित खेत के दौरे प्रदान करते हैं जहां आप हमारी टिकाऊ खेती की प्रथाओं को कार्य में देख सकते हैं। दौरे सप्ताहांत में उपलब्ध हैं और हमारी वेबसाइट के माध्यम से या सीधे हमें कॉल करके बुक किए जा सकते हैं।',
    'faqpage.q4': 'क्या आप कोई रसायन या कीटनाशक का उपयोग करते हैं?',
    'faqpage.a4': 'नहीं, हम 100% जैविक खेती की प्रथाओं के लिए प्रतिबद्ध हैं। हम प्राकृतिक कीट नियंत्रण विधियों, साथी रोपण और जैविक खाद का उपयोग करते हैं ताकि हमारी उपज रसायन-मुक्त और खपत के लिए सुरक्षित हो।',
    'faqpage.q5': 'क्या आप जैविक बीज या पौधे बेचते हैं?',
    'faqpage.a5': 'हां, हम जैविक बीज और स्टार्टर पौधों की विभिन्न किस्में बेचते हैं। हमारी दुकान अनुभाग पर जाएं या खेत में आएं और घर की बागवानी के लिए उपयुक्त विरासत और जैविक किस्मों का चयन करें।',
    'faqpage.q6': 'मैं अपने खेत की उपज को प्रभावी ढंग से कैसे बाजार में ला सकता हूं?',
    'faqpage.a6': 'प्रभावी विपणन में एक मजबूत ऑनलाइन उपस्थिति बनाना, स्थानीय किसानों के बाजार में भाग लेना, एक सीएसए कार्यक्रम बनाना और अपने खेत की कहानी साझा करने और ग्राहकों से जुड़ने के लिए सोशल मीडिया का लाभ उठाना शामिल है।',
    'faqpage.q7': 'खेत पर खाद बनाने के क्या लाभ हैं?',
    'faqpage.a7': 'खाद बनाना मिट्टी को आवश्यक पोषक तत्वों से समृद्ध करता है, मिट्टी की संरचना और जल प्रतिधारण में सुधार करता है, रासायनिक खाद की आवश्यकता को कम करता है, और जैविक कचरे को लैंडफिल से दूर करने में मदद करता है, जो अधिक टिकाऊ खेती चक्र में योगदान देता है।',
    'faqpage.q8': 'मैं कीटों को जैविक रूप से कैसे प्रबंधित करूं?',
    'faqpage.a8': 'जैविक कीट प्रबंधन में लाभकारी कीटों का उपयोग, साथी रोपण, फसल चक्र, नीम के तेल जैसे प्राकृतिक स्प्रे का उपयोग, और कीटों और बीमारियों के खिलाफ पौधों के प्रतिरोध को बनाने के लिए स्वस्थ मिट्टी बनाए रखना शामिल है।',

    // Weather Component
    'weather.title': '🌤️ मौसम और सतर्कता',
    'weather.subtitle': 'अपनी खेती के लिए रीयल-टाइम मौसम सतर्कता प्राप्त करें',
    'weather.enterCity': 'शहर का नाम दर्ज करें',
    'weather.placeholder': 'उदा., दिल्ली, मुंबई, बेंगलुरु',
    'weather.getWeather': 'मौसम प्राप्त करें',
    'weather.loading': 'लोड हो रहा है...',
    'weather.temperature': 'तापमान',
    'weather.humidity': 'आर्द्रता',
    'weather.rainfall': 'वर्षा',
    'weather.windSpeed': 'हवा की गति',
    'weather.conditions': 'स्थितियां',
    'weather.highDisease': 'उच्च - रोग जोखिम',
    'weather.lowPest': 'कम - कीट जोखिम',
    'weather.normal': 'सामान्य',
    'weather.heavyRain': 'भारी बारिश',
    'weather.moderate': 'मध्यम',
    'weather.light': 'हल्का',
    'weather.strong': 'मजबूत',
    'weather.recommendation': 'खेती की सिफारिश',
    'weather.speak': '🔊 बोलें',
    'weather.alerts': 'मौसम सतर्कता',
    'weather.recommendations': 'सिफारिशें:',
    'weather.affectedCrops': 'प्रभावित फसलें:',
    'weather.actionRequired': '⚠️ कार्रवाई आवश्यक है',
    'weather.speakAlert': '🔊 सतर्कता बोलें',
    'weather.cropAlerts': '🌾 फसल-विशिष्ट सतर्कता',
    'weather.selectCrop': 'फसल चुनें',
    'weather.getCropAlerts': 'फसल सतर्कता प्राप्त करें',
    'weather.noAlerts': 'के लिए कोई विशिष्ट सतर्कता नहीं',
    'weather.favorable': 'स्थितियां अनुकूल हैं!',

    // Voice Assistant
    'voice.title': '🎤 खेती एआई सहायक',
    'voice.subtitle': 'आवाज या पाठ में कोई भी खेती प्रश्न पूछें',
    'voice.language': 'भाषा',
    'voice.crop': 'फसल (वैकल्पिक)',
    'voice.cropPlaceholder': 'उदा., मूंग, चावल',
    'voice.location': 'स्थान (वैकल्पिक)',
    'voice.locationPlaceholder': 'उदा., दिल्ली, पंजाब',
    'voice.askQuestion': 'अपना खेती प्रश्न पूछें...',
    'voice.typeOrSpeak': 'अपना प्रश्न टाइप करें या बोलें...',
    'voice.speak': 'बोलें',
    'voice.stop': 'रोकें',
    'voice.send': 'भेजें',
    'voice.howToWater': 'पानी कैसे दें?',
    'voice.howToFertilize': 'खाद कैसे लगाएं?',
    'voice.pestControl': 'कीट नियंत्रण?',
    'voice.whenToHarvest': 'कब काटें?',
    'voice.copy': 'कॉपी करें',
    'voice.tip': 'सुझाव:',
    'voice.tipText': 'बेहतर उत्तर के लिए एआई को अपनी फसल का नाम और स्थान बताएं।',
    'voice.english': 'अंग्रेजी',
    'voice.hindi': 'हिंदी',

    // Chatbot Component
    'chatbot.title': '🌾 किसानसाथी एआई',
    'chatbot.subtitle': 'आपका खेती सहायक',
    'chatbot.newChat': 'नई चैट',
    'chatbot.noConversations': 'अभी तक कोई बातचीत नहीं',
    'chatbot.clear': 'साफ करें',
    'chatbot.clearConfirm': 'सभी संदेश साफ करें?',
    'chatbot.cropSelection': 'फसल चयन',
    'chatbot.cropSelectionDesc': 'कौन सी फसल लगाऊं?',
    'chatbot.fertilizer': 'खाद',
    'chatbot.fertilizerDesc': 'खाद कैसे लगाएं?',
    'chatbot.diseaseHelp': 'रोग सहायता',
    'chatbot.diseaseHelpDesc': 'मेरी फसल में बीमारी है',
    'chatbot.weatherAdvice': 'मौसम सलाह',
    'chatbot.weatherAdviceDesc': 'आज बारिश आ सकती है',
    'chatbot.placeholder': 'फसलों, खाद, बीमारियों, मौसम के बारे में पूछें...',
    'chatbot.speak': 'बोलें',
    'chatbot.copy': 'कॉपी करें',
    'chatbot.uploadFile': 'छवि या पीडीएफ अपलोड करें',
    'chatbot.errorConnecting': 'सर्वर से कनेक्ट करने में त्रुटि',
    'chatbot.errorProcessing': 'संदेश प्रोसेस करने में त्रुटि',

    // Banner Component
    'banner.clientsReview': '100K+ ग्राहक सकारात्मक समीक्षा के साथ',
    'banner.healthyLife': 'ताजे उत्पादों के साथ स्वस्थ जीवन',
    'banner.organic': 'जैविक',
    'banner.farming': 'खेती',
    'banner.vegetables': 'सब्जियां',
    'banner.agro': 'कृषि',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
